version: '3.8'
services:
  exercise-guide:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./build:/usr/share/nginx/html:ro
    restart: unless-stopped
