[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/exercise/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]  
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
